### ISSUE TITLE
How to run the example

### ISSUE THREAD

**Issue by KhoaLyDang** [seabeam/yuu_ahb#3]
Hi,
I am new to Verification IPs, could you tell me what is the value of "${ADD}" and "${CASE}" variable in the Makefile of the example in the /sim folder? Thanks.

**Comment by seabeam** [comment]
> Hi,
> I am new to Verification IPs, could you tell me what is the value of "${ADD}" and "${CASE}" variable in the Makefile of the example in the /sim folder? Thanks.

Have had COVID🤒

1.make clean comp
2.make run CASE=xxx

**Comment by KhoaLyDang** [comment]
Hi,
Thank you very much for the reply. Could you confirm that this project can
be ran on Questasim instead of vcs?

Thanks

Vào Th 4, 28 thg 12, 2022 lúc 10:29 seabeam ***@***.***> đã
viết:

**Comment by seabeam** [comment]
Hi Dang,

I have neither Mentor nor Cadence tools. All compile command included in Makefile, you can have a try to instead vcs options with vsim options

BR.
