### ISSUE TITLE
can't make run

### ISSUE THREAD

**Issue by seuh2** [seabeam/yuu_ahb#4]
hello，please tell more about how to start the project. I have tried as you said, but it reports "make simv :命令未找到"

**Comment by seuh2** [comment]
我在“simv”前加上了“./”，并按照测试列表测试，结果成功了。楼主要不要再加个查看波形和测试覆盖率的指令？

**Comment by seabeam** [comment]
interactive debug模式的话，run的时候加个+ADD=-gui吧， 或者自己写个菜单。
代码覆盖率的话，编译仿真都加上-cm line+tgl+fsm+cond+branch+assert, 仿真的时候再加-cm_name换个名字
