### ISSUE TITLE
ahb slave is_out judgment lack of condition

### ISSUE THREAD

**Issue by LitchiKnight** [seabeam/yuu_ahb#5]
Hi, 我在使用ahb slave功能时发现了一个问题，想请教一下。在ahb_slave_driver中的is_out()函数在driver每次驱动DUT前会进行判断，只有ahb的address超出所配置的maps的范围是会给req.response[0]赋ERROR。但是，由于response是random的，当response random成ERROR，但是此时address没有超出maps的范围，这里的判断条件无法将req.response[0]由ERROR修改成OKAY，进而导致ahb slave无法写入或读出数据。这里是否需要加上else分支，当address在maps范围内时，将OKAY赋给req.response[0]。
<img width="663" alt="屏幕截图 2024-05-09 194619" src="https://github.com/seabeam/yuu_ahb/assets/110707855/24d6c125-cde2-4fbf-822e-8d35f7a1adb4">

**Comment by seabeam** [comment]
hi. 在你的环境里response是在哪里random的？是自己写的sequence? 能否提供你的复现case?

**Comment by LitchiKnight** [comment]
我的sequence是直接派生自yuu_ahb_slave_sequence_base的。我最近突然看到你在yuu_slave_rsp_seqence中随机transaction的时候使用with对response进行了约束`response[0] == OKAY;`，而我的sequence中没有这样做。或许我也需要在我的sequence中加上对response的约束。
<img width="627" alt="屏幕截图 2024-05-20 172952" src="https://github.com/seabeam/yuu_ahb/assets/110707855/df350c53-1537-4537-a62f-3cba69e93616">

**Comment by seabeam** [comment]
> 我的sequence是直接派生自yuu_ahb_slave_sequence_base的。我最近突然看到你在yuu_slave_rsp_seqence中随机transaction的时候使用with对response进行了约束`response[0] == OKAY;`，而我的sequence中没有这样做。或许我也需要在我的sequence中加上对response的约束。 <img alt="屏幕截图 2024-05-20 172952" width="627" src="https://private-user-images.githubusercontent.com/110707855/332016965-df350c53-1537-4537-a62f-3cba69e93616.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTY1Njc2NTMsIm5iZiI6MTcxNjU2NzM1MywicGF0aCI6Ii8xMTA3MDc4NTUvMzMyMDE2OTY1LWRmMzUwYzUzLTE1MzctNDUzNy1hNjJmLTNjYmE2OWU5MzYxNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNTI0JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDUyNFQxNjE1NTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lNTY2NWU5NTAzNjllMzAxMzZlYjRjNjkwYTQzMDAwNTI0OWE2NmVmYjE1ZmQ1MDdhOTI5NzdmNTdhMTg1ZmQ4JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.yhtoa4IO2KhOVpkoHrtMQbls7kpsPwzgCxI8qHFAFHQ">

是的。这里可以从两方面看，首先目前版本的VIP并没有支持非常多的错误场景，而address out of range被强制认为是error。另外关于非address out of range但错误的场景，在test中并没有测试，因此不能保证driver一定支持。如果确实不支持，则需要自行派生driver重写drive_bus()以实现相应功能了。

那么我就close掉这个issue了，有其他问题请再联系
